[package]
name = "vit"
version = "1.0.0"
edition = "2021"

[dependencies]
image = "0.24.7"
crossterm = "0.27.0"
reqwest = { version = "0.11.23", features = ["blocking"] }
clap = { version = "4.4.11", features = ["derive"] }
